repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/hadialqattan/pycln.git
    rev: v2.3.0
    hooks:
      - id: pycln
        name: pycln (python)
        args: [--config=pyproject.toml]

  - repo: https://github.com/asottile/pyupgrade.git
    rev: v3.15.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle
        args:
          - --convention=google

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        name: mypy
        args:
          [
            --follow-imports=silent,
            --ignore-missing-imports,
            --show-column-numbers,
            --no-pretty,
            --strict,
          ]
        additional_dependencies: ["toml", "types-toml", "types-requests"]
        