services:
  dev-environment-python:
    build: .
    container_name: dev-environment-python
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ../:/workdir/
    environment:
      - DEV_CONTAINER=1
    networks:
      - ebl-net

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
        - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - ebl-net
    restart: always

networks:
  ebl-net:
    name: ebl-net
    external: true
